# File: .readthedocs.yaml

version: 2

sphinx:
  configuration: doc/conf.py

python:
  # Build on Python <= 3.12 to annoying cython / pyaml issues:
  # https://stackoverflow.com/questions/77490435/attributeerror-cython-sources
  version: 3.11
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build PDF & ePub
formats:
  - epub
  - pdf
